### ISSUE TITLE
请教原理

### ISSUE THREAD

**Issue by seed93** [jedmeng/python-oppleio#1]
您好，很感谢您对欧普有这么深度的解析。我现在有欧普灯具，但是通过中国移动宽带的网络无法连接，所以想了解一下具体的原理，看是否能有其他方法解决。python的代码里大概是发了一个广播然后根据返回信息来配网。我看欧普本身是ap模式，这个怎么理解呢？以及如何做到不依赖公网，只依赖局域网的呢？python代码里好像也没有依赖公网就可以实现连接和控制了。
感谢！

**Comment by jedmeng** [comment]
这个插件只是控制设备，和配网没关系。配网需要通过手机APP完成。

**Comment by jedmeng** [comment]
在无法连接公网的情况下，依然可以尝试使用手机APP进行配网，即便提示失败也没关系。大部分情况下失败只是由于服务器未检测到连接的设备，但此时设备已经连接上WIFI（可以通过路由器的已连接设备中查看确认）。连接后即可通过此插件进行控制。
